name: Tag version

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SemVer
      run: npm install semver
      
    - name: Version  
      id: version  
      uses: juliansangillo/tag-version@v1  
      with:  
          production-branch: master  
          test-branch: test  
          dev-branch: develop 
