name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Show branches
      run: git branch -a
    
    - name: Check if repository is empty
      run: git log -1

    - name: Get last commit message
      run: git log -1 --pretty=%B
    
    - name: Show all tags
      run: git tag

    - name: Get last tag
      run: |
        git config --global user.email "gabriel.godoybz@hotmail.com"
        git config --global user.name "GabrielGodoy01"
        git fetch --prune --unshallow
        git describe --abbrev=0 --tags
      
    - name: Incrementar versão
      run: |
        VERSION=$(git describe --abbrev=0 --tags)
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        if [[ $LAST_COMMIT_MESSAGE == *"major"* ]]; then
            major=$(echo $VERSION | awk -F. '{print $1}')
            major=$((major + 1))
            NEW_VERSION="$major.0.0"
        elif [[ $LAST_COMMIT_MESSAGE == *"minor"* ]]; then
            NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$2+=1;print}')
        else
            NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
        fi
        git tag $NEW_VERSION
        git push --tags
