name: Increment Version

on:
  push:
    branches:
      - master

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Show branches
      run: git branch -a
    
    - name: Check if repository is empty
      run: git log -1

    - name: Get last commit message
      run: git log -1 --pretty=%B
    
    - name: Show all tags
      run: git tag

    - name: Get last tag
      run: |
        git config --global user.email "gabriel.godoybz@hotmail.com"
        git config --global user.name "GabrielGodoy01"
        git fetch --prune --unshallow
        git describe --abbrev=0 --tags
      
    - name: Increment version
      run: |
        last_commit_msg=$(git log -1 --pretty=%B)
        last_tag=$(git describe --abbrev=0 --tags)
        if [[ $last_commit_msg == *"fix:"* ]]; then
          new_version=$last_tag.1
        elif [[ $last_commit_msg == *"feat:"* ]]; then
          new_version=$last_tag.1
        else
          new_version=$last_tag.0
        fi
        echo "::set-output name=new_version::$new_version"
    
    - name: Commit and push changes
      run: |
        git config --global user.email "gabriel.godoybz@hotmail.com"
        git config --global user.name "GabrielGodoy01"
        git tag ${{ steps.increment_version.outputs.new_version }}
        git push origin --tags
        echo "New version: ${{ steps.increment_version.outputs.new_version }}"
